#!/usr/bin/env python3
"""Regenerate handouts/fonts.css with the brand fonts embedded as base64.

The handout PDFs have to carry their own fonts — there's no network at print
time, and a PDF that falls back to Arial isn't on brand. This pulls the latin
subsets of Geist (display and body) and Caveat (the signature) from Google
Fonts and inlines them.

Only needs re-running if the brand type changes in
getluckyjo/entrepreneurcoach → DESIGN.md. The committed fonts.css is what
scripts/build-handouts.py actually reads.

    ./scripts/fetch-fonts.py
"""

import base64
import pathlib
import re
import sys
import urllib.error
import urllib.request

UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)

# Matches --font-display / --font-sans / --font-script in the site's global.css
FAMILIES = [
    ("Geist", "wght@400;600;700"),
    ("Caveat", "wght@700"),
]

OUT = pathlib.Path(__file__).resolve().parent.parent / "handouts" / "fonts.css"


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    return urllib.request.urlopen(req, timeout=30).read()


def main():
    blocks = []
    for family, weights in FAMILIES:
        try:
            css = fetch(
                f"https://fonts.googleapis.com/css2?family={family}:{weights}&display=swap"
            ).decode()
        except urllib.error.URLError as err:
            sys.exit(f"Error: couldn't reach Google Fonts for {family} ({err}).")

        # Google returns one @font-face per subset, each preceded by a comment
        # naming it. We only want latin — latin-ext and the rest triple the size
        # for glyphs no handout uses.
        faces = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
        kept = 0
        for subset, block in faces:
            if subset != "latin":
                continue
            url_match = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            if not url_match:
                continue
            b64 = base64.b64encode(fetch(url_match.group(1))).decode()
            block = block.replace(
                url_match.group(0), f"url(data:font/woff2;base64,{b64})"
            )
            blocks.append(block)
            kept += 1
        if not kept:
            sys.exit(f"Error: no latin subset found for {family}.")
        print(f"  {family}: {kept} face(s)")

    OUT.write_text(
        "/* Brand fonts, embedded for print. Generated by scripts/fetch-fonts.py —\n"
        "   do not edit by hand. Sources: Geist and Caveat, latin subset only. */\n"
        + "\n".join(blocks)
        + "\n"
    )
    print(f"\nWrote {OUT.name} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
